language: node_js
services: mongodb
node_js:
    - "stable"
cache:
    directories:
        - node_modules
script:
   - cd server && npm install && npm test
   - cd ../client && npm install && npm test
