module.exports = {
  USER_PROFILE_ADD_FRIENDSHIP: "USER_PROFILE_ADD_FRIENDSHIP",
  USER_PROFILE_UPDATE_FRIENDSHIP: "USER_PROFILE_UPDATE_FRIENDSHIP",
  USER_PROFILE_DELETE_FRIENDSHIP: "USER_PROFILE_ADD_FRIENDSHIP"
};
