module.exports = {
  USER_PROFILE_ADD_FRIENDSHIP: "USER_PROFILE_ADD_FRIENDSHIP",
  USER_PROFILE_UPDATE_FRIENDSHIP: "USER_PROFILE_UPDATE_FRIENDSHIP",
  USER_PROFILE_DELETE_FRIENDSHIP: "USER_PROFILE_DELETE_FRIENDSHIP",
  USER_PROFILE_MARK_FRIENDSHIPS_SEEN: "USER_PROFILE_MARK_FRIENDSHIPS_SEEN",

  ONLINE_FRIENDS_SET: "ONLINE_FRIENDS_SET",
  ONLINE_FRIENDS_ADD: "ONLINE_FRIENDS_ADD",
  ONLINE_FRIENDS_REMOVE: "ONLINE_FRIENDS_REMOVE"
};
