export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_USER = "AUTH_USER";
export const AUTH_INIT = "AUTH_INIT";
export const AUTH_LOAD = "AUTH_LOAD";
export const AUTH_LOGOUT_INIT = "AUTH_LOGOUT_INIT";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_REGISTER_INIT = "AUTH_REGISTER_INIT";
export const AUTH_RESET_ERROR = "AUTH_RESET_ERROR";
export const AUTH_FIRST_LOGIN = "AUTH_FIRST_LOGIN";

export const PROFILE_GET_INFO = "PROFILE_GET_INFO";
export const PROFILE_SET_INFO = "PROFILE_SET_INFO";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_LOAD = "PROFILE_LOAD";
export const PROFILE_RESET_ERROR = "PROFILE_RESET_ERROR";

export const PROFILE_MODAL_INIT = "PROFILE_MODAL_INIT";
export const PROFILE_MODAL_CONTINUE = "PROFILE_MODAL_CONTINUE";
export const PROFILE_MODAL_CLOSE = "PROFILE_MODAL_CLOSE";
export const PROFILE_MODAL_UPDATE = "PROFILE_MODAL_UPDATE";

export const RESET = "RESET";
