export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_INIT = "AUTH_INIT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_FIRST_LOGIN = "AUTH_FIRST_LOGIN";

export const USER_PROFILE_GET_INFO = "PROFILE_GET_INFO";
export const USER_PROFILE_SET_INFO = "PROFILE_SET_INFO";
export const USER_PROFILE_UPDATE = "PROFILE_UPDATE";

export const USER_PROFILE_MODAL_INIT = "PROFILE_MODAL_INIT";
export const USER_PROFILE_MODAL_CONTINUE = "PROFILE_MODAL_CONTINUE";
export const USER_PROFILE_MODAL_CLOSE = "PROFILE_MODAL_CLOSE";
export const USER_PROFILE_MODAL_UPDATE = "PROFILE_MODAL_UPDATE";

export const RESET = "RESET";

export const PROFILE_GET = "PROFILE_GET";
export const PROFILE_GET_SUCCESS = "PROFILE_GET_SUCCESS";

export const PROFILE_POSTS_GET = "POSTS_GET";
export const POSTS_GET_SUCCESS = "POSTS_GET_SUCCESS";

export const POSTS_CREATE = "POSTS_CREATE";
export const POSTS_CREATE_SUCCESS = "POSTS_CREATE_SUCCESS";

export const POSTS_UPDATE = "POSTS_UPDATE";
export const POSTS_UPDATE_SUCCESS = "POSTS_UPDATE_SUCCESS";

export const POSTS_DELETE = "POSTS_DELETE";
export const POSTS_DELETE_SUCCESS = "POSTS_DELETE_SUCCESS";

export const POST_COMMENTS_GET = "POST_COMMENTS_GET";
export const POST_COMMENTS_GET_SUCCESS = "POST_COMMENTS_GET_SUCCESS";

export const POSTS_COMMENT_CREATE_SUCCESS = "POSTS_COMMENT_CREATE_SUCCESS";
